
# Profile: Manuscript
# We're not using this rn because it turns all the notebooks into Jupiter Notebooks, which is very annoying. 
# But we're probably losing some functionality as a consequence. 


project:
  type: manuscript
  output-dir: _manuscript

manuscript:
  article: index.qmd

format:
  html:
    code-fold: true
    fig-format: svg
    toc: true
    comments:
      hypothesis: true
  # docx: default
  # jats: default
  # pdf: default

execute:
  freeze: false
  keep-ipynb: false

engine: knitr